### Numpy

In [1]:
#  First import the library using the following code:

import numpy as np

In [3]:
age_list = list(np.random.randint(20,60,10))
print(type(age_list))
print(age_list)

<class 'list'>
[37, 30, 49, 51, 21, 51, 56, 52, 54, 45]


In [6]:
# 1D Array

age_array = np.array(age_list)
print(type(age_array))

print(age_array)

print(age_array.ndim)  # Provides the dimention of the array
print(age_array.size)  # Provides the number of elements in the array
print(age_array.shape) # Provides the shape of the array

<class 'numpy.ndarray'>
[37 30 49 51 21 51 56 52 54 45]
1
10
(10,)


In [20]:
# 2D Array
two_array = age_array.reshape(2,5)
print(two_array)

[[37 30 49 51 21]
 [51 56 52 54 45]]


In [9]:
books = np.array(['Python for Data Science', 'Intro to machine learning', 'Intro to deep learning'])

print(books)
print(type(books))
print("The shape of the array is:", books.shape)

['Python for Data Science' 'Intro to machine learning'
 'Intro to deep learning']
<class 'numpy.ndarray'>
The shape of the array is: (3,)


** Random()** is used to create random numbers. It will create the random numbers from [0.0,1.0]

In [19]:
one_rand_nos = np.random.random(size=20)
print(one_rand_nos)



two_rand_nos = np.random.random(size = (3,4))
print("\n", two_rand_nos)


two_rand = one_rand_nos[:12].reshape(4,3)
print("\n", two_rand)

[0.62843018 0.31910745 0.93920798 0.43898874 0.43452794 0.14896797
 0.39236323 0.52456794 0.78059676 0.19262666 0.74546192 0.55335213
 0.62982587 0.33711049 0.73889103 0.62128994 0.90578229 0.58875456
 0.09384136 0.50287687]

 [[0.66655932 0.35707175 0.44622681 0.14264642]
 [0.07326907 0.36368847 0.62107155 0.241543  ]
 [0.91704404 0.38160358 0.56791903 0.72063244]]

 [[0.62843018 0.31910745 0.93920798]
 [0.43898874 0.43452794 0.14896797]
 [0.39236323 0.52456794 0.78059676]
 [0.19262666 0.74546192 0.55335213]]


In [29]:
# Three Dimentional Array:

three_rand_nos = np.random.random(size=(3,4,4))
print(three_rand_nos)

[[[0.9806049  0.68684923 0.30222219 0.45861507]
  [0.7656689  0.66899743 0.51957525 0.6658756 ]
  [0.73941997 0.51675016 0.4401825  0.87534507]
  [0.18877491 0.12330368 0.43724839 0.36272571]]

 [[0.82382372 0.1620831  0.06276643 0.07398941]
  [0.06787806 0.39239774 0.74251547 0.95666302]
  [0.56986208 0.60881914 0.57090983 0.20357907]
  [0.31289672 0.98408098 0.09149755 0.78691551]]

 [[0.0759     0.08478483 0.83651332 0.41023432]
  [0.93876831 0.73744962 0.87770044 0.55982613]
  [0.79177485 0.76624698 0.19975264 0.18491354]
  [0.56223021 0.08168675 0.28862829 0.9284761 ]]]


In [32]:
print("The size of 3D array:", three_rand_nos.size)
print("\nThe Dimension of 3D array:", three_rand_nos.ndim)
print("\nThe shape of the array is:", three_rand_nos.shape)

The size of 3D array: 48

The Dimension of 3D array: 3

The shape of the array is: (3, 4, 4)


In [106]:
np.random.randint(-20,-10,10)

array([-15, -13, -12, -11, -12, -12, -15, -16, -19, -20])

In [36]:
np.random.rand(10)

array([0.37062453, 0.29781758, 0.38039528, 0.96688556, 0.60669103,
       0.23057785, 0.04029451, 0.50876995, 0.41554769, 0.3994702 ])

In [41]:
odd_nos = np.arange(1,101,2)
print(odd_nos)

even_nos = np.arange(0,100,2)
print("\n",even_nos)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]

 [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [52]:
# Creating evenly spaced numbers using linspace:
print(np.linspace(0,100,5))
print(np.linspace(0,100,10))


# Creating zero array
print(np.zeros(10))    # It can be only 1-dimension array.
print(np.zeros((10,2)),int)

# Creating one array
print(np.ones(10))     # It can be only 1-dimension array.

[  0.  25.  50.  75. 100.]
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] <class 'int'>
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [53]:
# Creating the 3 x 3 matrix

print(np.full((3,4), fill_value=5))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [54]:
# Creating the identity matrix:

print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [58]:
# np.eye (Rows, columns, Identify index):

np.eye(4,5,0)    # It will also create the identity matrix with identity in the kth index

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [59]:
another_arr = np.random.randint(10,100,20).reshape(5,4)
print(another_arr)

[[92 12 51 37]
 [54 42 63 78]
 [14 97 70 78]
 [49 13 67 46]
 [70 30 14 93]]


In [62]:
# Matrix multiplication Matrix

another_arr.dot(np.eye(4,5,0))

array([[92., 12., 51., 37.,  0.],
       [54., 42., 63., 78.,  0.],
       [14., 97., 70., 78.,  0.],
       [49., 13., 67., 46.,  0.],
       [70., 30., 14., 93.,  0.]])

In [67]:
odd_number = np.array([1,3,5,7]).reshape(2,2)
even_number = np.array([8,6,2,4]).reshape(2,2)

print(odd_number,"\n\n",even_number)

[[1 3]
 [5 7]] 

 [[8 6]
 [2 4]]


In [71]:
#  Multiplication of two arrays:
print(odd_number * even_number)


# Scalar Multiplication:
print("\n\n",odd_number * 5)

[[ 8 18]
 [10 28]]


 [[ 5 15]
 [25 35]]


In [72]:
# Matrix Multiplication:

print(odd_number.dot(even_number))

[[14 18]
 [54 58]]


In [91]:
salaries = np.random.randint(10000,1000000,60).reshape(6,10)
print(salaries)

[[619167 470180 906712  85909 345098 660960 432778  46820 951989 859146]
 [759916  56906 785944 966892 963826 422108 921406 916359  47753 341066]
 [957996 454852  83426 428363 788684 379600 370575 528242  62185 485640]
 [672264 617485 288385 992043 679746 283984 704932 645607 535654 769380]
 [562602 397555 838750 917403 928314 803781 487683  98211 565671 665603]
 [512269 529617 789302  52477 360007  36804 961919  93351 159293 956361]]


In [95]:
my_matrix = np.random.randint(10,20,16).reshape(4,4)
my_matrix

array([[15, 17, 15, 16],
       [19, 18, 11, 10],
       [18, 10, 10, 14],
       [19, 11, 19, 17]])

In [96]:
np.flip(my_matrix)

array([[17, 19, 11, 19],
       [14, 10, 10, 18],
       [10, 11, 18, 19],
       [16, 15, 17, 15]])

In [97]:
np.flipud(my_matrix)

array([[19, 11, 19, 17],
       [18, 10, 10, 14],
       [19, 18, 11, 10],
       [15, 17, 15, 16]])

In [102]:
print(np.flip(my_matrix,0))

print("\n",np.flip(my_matrix,1))

[[19 11 19 17]
 [18 10 10 14]
 [19 18 11 10]
 [15 17 15 16]]

 [[16 15 17 15]
 [10 11 18 19]
 [14 10 10 18]
 [17 19 11 19]]
